apiVersion: apps/v1
kind: Deployment
metadata:
  name: pearl-bo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pearl-bo
  template:
    metadata:
      labels:
        app: pearl-bo
    spec:
      containers:
        - name: pearl-bo
          image: ddecrulle/pearl-jam-back-office:latest
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=prod -Dspring.config.location=classpath:/,${CATALINA_BASE}/webapps/pearljambo.properties -Dlogging.config=classpath:log4j2.xml"
